#!/usr/bin/bash
sddmConf="/usr/lib/sddm/sddm.conf.d/default.conf"

if [ -f /etc/sddm.conf.d/kde_settings.conf ]; then
    sddmConf="/etc/sddm.conf.d/kde_settings.conf"
fi

if [ "$1" == "plasma" ]; then
    NEW_SESSION="plasma" # For other desktops, change here.
    sudo sed -i "s/^Session=.*/Session=plasma/" "$sddmConf"
    steam -shutdown
elif [ "$1" == "gamescope" ]; then
    sudo sed -i "s/^Session=.*/Session=gamescope-session-steam/" "$sddmConf"
    dbus-send --session --type=method_call --print-reply --dest=org.kde.Shutdown /Shutdown org.kde.Shutdown.logout
else
    exit
fi