#!/usr/bin/bash

# Espera a que tengas red
until ping -c1 1.1.1.1 &>/dev/null; do
  echo "Esperando conexión a Internet..."
  sleep 1
done

# Una vez conectado, actualiza
echo "Conexión detectada. Iniciando actualización..."


sddmConf="/etc/sddm.conf.d/kde_settings.conf"

if [ "$1" == "plasma" ]; then
    NEW_SESSION="plasma" # For other desktops, change here.
    sudo sed -i "s/^Session=.*/Session=plasma/" "$sddmConf"
    steam -shutdown
elif [ "$1" == "gamescope" ]; then
    sudo sed -i "s/^Session=.*/Session=gamescope-session-steam/" "$sddmConf"
    dbus-send --session --type=method_call --print-reply --dest=org.kde.Shutdown /Shutdown org.kde.Shutdown.logout
else
    exit
fi